// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package visual

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// newMockworkerLauncher creates a new instance of mockworkerLauncher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerLauncher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerLauncher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockworkerLauncher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockworkerLauncher is an autogenerated mock type for the workerLauncher type
type mockworkerLauncher struct {
	mock.Mock
}

type mockworkerLauncher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerLauncher) EXPECT() *mockworkerLauncher_Expecter {
	return &mockworkerLauncher_Expecter{mock: &_m.Mock}
}

// launch provides a mock function for the type mockworkerLauncher
func (_mock *mockworkerLauncher) launch(ctx context.Context) (workerProcess, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for launch")
	}

	var r0 workerProcess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (workerProcess, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) workerProcess); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workerProcess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerLauncher_launch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'launch'
type mockworkerLauncher_launch_Call struct {
	*mock.Call
}

// launch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockworkerLauncher_Expecter) launch(ctx any) *mockworkerLauncher_launch_Call {
	return &mockworkerLauncher_launch_Call{Call: _e.mock.On("launch", ctx)}
}

func (_c *mockworkerLauncher_launch_Call) Run(run func(ctx context.Context)) *mockworkerLauncher_launch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerLauncher_launch_Call) Return(workerProcessMoqParam workerProcess, err error) *mockworkerLauncher_launch_Call {
	_c.Call.Return(workerProcessMoqParam, err)
	return _c
}

func (_c *mockworkerLauncher_launch_Call) RunAndReturn(run func(ctx context.Context) (workerProcess, error)) *mockworkerLauncher_launch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerProcess creates a new instance of mockworkerProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerProcess {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockworkerProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockworkerProcess is an autogenerated mock type for the workerProcess type
type mockworkerProcess struct {
	mock.Mock
}

type mockworkerProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerProcess) EXPECT() *mockworkerProcess_Expecter {
	return &mockworkerProcess_Expecter{mock: &_m.Mock}
}

// kill provides a mock function for the type mockworkerProcess
func (_mock *mockworkerProcess) kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerProcess_kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'kill'
type mockworkerProcess_kill_Call struct {
	*mock.Call
}

// kill is a helper method to define mock.On call
func (_e *mockworkerProcess_Expecter) kill() *mockworkerProcess_kill_Call {
	return &mockworkerProcess_kill_Call{Call: _e.mock.On("kill")}
}

func (_c *mockworkerProcess_kill_Call) Run(run func()) *mockworkerProcess_kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerProcess_kill_Call) Return(err error) *mockworkerProcess_kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerProcess_kill_Call) RunAndReturn(run func() error) *mockworkerProcess_kill_Call {
	_c.Call.Return(run)
	return _c
}

// pipes provides a mock function for the type mockworkerProcess
func (_mock *mockworkerProcess) pipes() (io.WriteCloser, io.ReadCloser) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for pipes")
	}

	var r0 io.WriteCloser
	var r1 io.ReadCloser
	if returnFunc, ok := ret.Get(0).(func() (io.WriteCloser, io.ReadCloser)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.WriteCloser); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() io.ReadCloser); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}
	return r0, r1
}

// mockworkerProcess_pipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'pipes'
type mockworkerProcess_pipes_Call struct {
	*mock.Call
}

// pipes is a helper method to define mock.On call
func (_e *mockworkerProcess_Expecter) pipes() *mockworkerProcess_pipes_Call {
	return &mockworkerProcess_pipes_Call{Call: _e.mock.On("pipes")}
}

func (_c *mockworkerProcess_pipes_Call) Run(run func()) *mockworkerProcess_pipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerProcess_pipes_Call) Return(stdin io.WriteCloser, stdout io.ReadCloser) *mockworkerProcess_pipes_Call {
	_c.Call.Return(stdin, stdout)
	return _c
}

func (_c *mockworkerProcess_pipes_Call) RunAndReturn(run func() (io.WriteCloser, io.ReadCloser)) *mockworkerProcess_pipes_Call {
	_c.Call.Return(run)
	return _c
}

// wait provides a mock function for the type mockworkerProcess
func (_mock *mockworkerProcess) wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerProcess_wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'wait'
type mockworkerProcess_wait_Call struct {
	*mock.Call
}

// wait is a helper method to define mock.On call
func (_e *mockworkerProcess_Expecter) wait() *mockworkerProcess_wait_Call {
	return &mockworkerProcess_wait_Call{Call: _e.mock.On("wait")}
}

func (_c *mockworkerProcess_wait_Call) Run(run func()) *mockworkerProcess_wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerProcess_wait_Call) Return(err error) *mockworkerProcess_wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerProcess_wait_Call) RunAndReturn(run func() error) *mockworkerProcess_wait_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfadeRunner creates a new instance of mockfadeRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfadeRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfadeRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockfadeRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockfadeRunner is an autogenerated mock type for the fadeRunner type
type mockfadeRunner struct {
	mock.Mock
}

type mockfadeRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfadeRunner) EXPECT() *mockfadeRunner_Expecter {
	return &mockfadeRunner_Expecter{mock: &_m.Mock}
}

// RunFade provides a mock function for the type mockfadeRunner
func (_mock *mockfadeRunner) RunFade(ctx context.Context, m *fadeModel) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for RunFade")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fadeModel) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockfadeRunner_RunFade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunFade'
type mockfadeRunner_RunFade_Call struct {
	*mock.Call
}

// RunFade is a helper method to define mock.On call
//   - ctx context.Context
//   - m *fadeModel
func (_e *mockfadeRunner_Expecter) RunFade(ctx any, m any) *mockfadeRunner_RunFade_Call {
	return &mockfadeRunner_RunFade_Call{Call: _e.mock.On("RunFade", ctx, m)}
}

func (_c *mockfadeRunner_RunFade_Call) Run(run func(ctx context.Context, m *fadeModel)) *mockfadeRunner_RunFade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fadeModel
		if args[1] != nil {
			arg1 = args[1].(*fadeModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfadeRunner_RunFade_Call) Return(err error) *mockfadeRunner_RunFade_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockfadeRunner_RunFade_Call) RunAndReturn(run func(ctx context.Context, m *fadeModel) error) *mockfadeRunner_RunFade_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklockRunner creates a new instance of mocklockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklockRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocklockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocklockRunner is an autogenerated mock type for the lockRunner type
type mocklockRunner struct {
	mock.Mock
}

type mocklockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklockRunner) EXPECT() *mocklockRunner_Expecter {
	return &mocklockRunner_Expecter{mock: &_m.Mock}
}

// RunLock provides a mock function for the type mocklockRunner
func (_mock *mocklockRunner) RunLock(ctx context.Context, cfg lockConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for RunLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, lockConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocklockRunner_RunLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunLock'
type mocklockRunner_RunLock_Call struct {
	*mock.Call
}

// RunLock is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg lockConfig
func (_e *mocklockRunner_Expecter) RunLock(ctx any, cfg any) *mocklockRunner_RunLock_Call {
	return &mocklockRunner_RunLock_Call{Call: _e.mock.On("RunLock", ctx, cfg)}
}

func (_c *mocklockRunner_RunLock_Call) Run(run func(ctx context.Context, cfg lockConfig)) *mocklockRunner_RunLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 lockConfig
		if args[1] != nil {
			arg1 = args[1].(lockConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocklockRunner_RunLock_Call) Return(err error) *mocklockRunner_RunLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocklockRunner_RunLock_Call) RunAndReturn(run func(ctx context.Context, cfg lockConfig) error) *mocklockRunner_RunLock_Call {
	_c.Call.Return(run)
	return _c
}
